spring.application.name=url-shortening-service

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/url_shortening}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false