CREATE TABLE shortened_urls
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url TEXT                     NOT NULL,
    short_code   VARCHAR(20)              NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    access_count BIGINT                   NOT NULL DEFAULT 0,

    CONSTRAINT uk_shortened_urls_short_code UNIQUE (short_code),
    CONSTRAINT ck_shortened_urls_access_count CHECK (access_count >= 0)
);